export const GET_BROWSE_LIST = "GET_BROWSE_LIST";
export const GET_BROWSE_LIST_DONE = "GET_BROWSE_LIST_DONE";
export const GET_SEARCH_LIST = "GET_SEARCH_LIST";
export const GET_SEARCH_LIST_DONE = "GET_SEARCH_LIST_DONE";

//Form
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";